### ISSUE TITLE
Come funziona? 

### ISSUE THREAD

**Issue by barbax7** [pperliti/pagopa-rt#2]
Ciao
Sto cercando un modo per convertire una  RT in formato xml in una versione più user friendly e ho trovato il tuo progetto.
Non riesco a capire però come va utilizzato, non conoscendo bene il linguaggio.

Puoi fare una breve sintesi da mettere nel readme?

**Comment by pperliti** [comment]
Il file `RT.jrxml` è un semplice report utilizzabile tramite la libreria open-source (Java) JasperReports.
In estrema sintesi devi:
- utilizzare la libreria per caricare il report (template *.jrxml)
- compilare il report
- alimentare il report con la ricevuta telematica
- esportare il risultato in PDF (o altro formato)

Sul web trovi parecchi tutorial su come fare (se vuoi puoi anche scaricare l'editor gratuito JasperSoft Studio per farti un'idea del risultato senza dover programmare esplicitamente, dai un'occhiata [qui](https://community.jaspersoft.com/wiki/xml-datasources-jaspersoft-studio)).

Sotto trovi un esempio di pseudo-codice (non l'ho testato ma dovrebbe funzionare):

```
String reportFileName = "<PATH_TO_FILE_JRXML";
String rtFileName = "<PATH_TO_FILE_RT";

Map<String,Object> reportParameters = new HashMap<String,Object>();

/* Si passa la ricevuta telematica come parametro del report, il quale lo utilizza come datasource XML */
Document document = JRXmlUtils.parse(rtFileName);
reportParameters.put(JRXPathQueryExecuterFactory.PARAMETER_XML_DATA_DOCUMENT, document);
reportParameters.put(JRXPathQueryExecuterFactory.XML_DATE_PATTERN, "yyyy-MM-dd"); // "yyyy-MM-dd'T'HH:mm:ss" va in errore
reportParameters.put(JRXPathQueryExecuterFactory.XML_NUMBER_PATTERN, "###,##0.00");
reportParameters.put(JRXPathQueryExecuterFactory.XML_LOCALE, Locale.ENGLISH); // IMPORTANTE! Non mettere ITALIAN (la formattazione dei numeri risulterebbe sbagliata, invertendo i separatori di migliaia e decimali)
reportParameters.put(JRParameter.REPORT_LOCALE, Locale.ITALIAN);


/* Popolamento report */
try (ByteArrayOutputStream baos = new ByteArrayOutputStream())
{
   JasperReport mainReport = JasperCompileManager.compileReport(reportFileName);
   JasperPrint print = JasperFillManager.fillReport(mainReport, reportParameters);
   JRPdfExporter pdfExporter = new JRPdfExporter();
   pdfExporter.setExporterInput(new SimpleExporterInput(print));
   pdfExporter.setExporterOutput(new SimpleOutputStreamExporterOutput(baos));
   pdfExporter.exportReport();
   return baos.toByteArray(); // as is
}
```
